### ISSUE TITLE
Tippy css for light mode only with Furo

### ISSUE THREAD

**Issue by vict0rsch** [sphinx-extensions2/sphinx-tippy#8]
Hello,

first of all, thanks for the package!

I'm having an issue where I want to only change the tippy's css when Furo is in Light mode. The tippys are fine in Dark mode but not readable in Light mode:

Link issue:

![SCR-20230831-isxt](https://github.com/sphinx-extensions2/sphinx-tippy/assets/9283470/dd83dffe-cac3-4a07-ae88-41d593470ad0)

Inline code issue:
![SCR-20230831-iswx](https://github.com/sphinx-extensions2/sphinx-tippy/assets/9283470/85e7b192-1cac-46e2-bfbb-aeb59f1af940)

Any advice on how to procede?

Thanks!

**Comment by dbitouze** [comment]
Well, in fact, it is enough in the case of [PyData-Sphinx-Theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/) to follow the “Important” admonition [here](https://sphinx-tippy.readthedocs.io/en/latest/#usage).

**Comment by lkubb** [comment]
The following CSS improves basic compatibility with `furo` and can be [applied as documented](https://sphinx-tippy.readthedocs.io/en/latest/#usage):

```css
.tippy-box {
    background-color: var(--color-background-hover);
    color: var(--color-foreground-primary);
    border: 1px solid var(--color-foreground-border);
}
```

More `furo` color variables: https://github.com/pradyunsg/furo/blob/main/src/furo/assets/styles/variables/_colors.scss
